const form=document.getElementById('intake'),steps=[...document.querySelectorAll('.step')];let step=0;
const labels=['Business','Operations','Systems','Discovery','Privacy','Confirm'];
const modules=['core_office','voice','sms','estimating','invoicing','scheduling','supplier_recon','field_app','cad_blueprints','hiring','advertising','reviews','custom'];
document.getElementById('modules').innerHTML=modules.map(m=>`<label><input type="checkbox" name="module" value="${m}">${m.replaceAll('_',' ')}</label>`).join('');
function lines(name){return (form.elements[name]?.value||'').split(/\n|,/).map(x=>x.trim()).filter(Boolean)}
function payload(){const f=form.elements;return {schema_version:1,business:{company_name:f.company_name.value,owner_name:f.owner_name.value,primary_email:f.primary_email.value,primary_phone:f.primary_phone.value,website:f.website.value,industry:f.industry.value,timezone:f.timezone.value,service_area:f.service_area.value,jurisdiction:f.jurisdiction.value,team_size:Number(f.team_size.value)||1},operations:{services:lines('services'),pain_points:lines('pain_points'),office_workflows:lines('office_workflows'),field_workflows:lines('field_workflows'),approval_preferences:f.approval_preferences.value},systems:{email:lines('email'),phone_sms:lines('phone_sms'),crm:lines('crm'),accounting:lines('accounting'),calendar:lines('calendar'),payments:lines('payments'),suppliers:lines('suppliers'),other:lines('other')},discovery:{public_website_authorized:f.public_website_authorized.checked,website_url:f.website.value,allowed_public_sources:lines('public_sources'),brand_assets:f.brand_assets.checked,crawl_notes:f.crawl_notes.value,authenticated_sources:[]},privacy:{infrastructure_preference:f.infrastructure_preference.value,automation_level:f.automation_level.value,retention_notes:f.retention_notes.value},modules:[...form.querySelectorAll('[name=module]:checked')].map(x=>x.value),uploads:[],consents:{terms:f.terms.checked,privacy:f.privacy.checked,public_discovery:f.public_discovery.checked,timestamp:new Date().toISOString()}}}
function render(){steps.forEach((s,i)=>s.classList.toggle('active',i===step));document.getElementById('bar').style.width=((step+1)/steps.length*100)+'%';document.getElementById('steps').textContent=`${step+1}/${steps.length} · ${labels[step]}`;document.getElementById('back').style.visibility=step?'visible':'hidden';document.getElementById('next').style.display=step===steps.length-1?'none':'inline-block';document.getElementById('submit').style.display=step===steps.length-1?'inline-block':'none';if(step===steps.length-1)document.getElementById('preview').textContent=JSON.stringify(payload(),null,2)}
document.getElementById('next').onclick=()=>{if(step===0&&!['company_name','owner_name','primary_email','website','industry','timezone'].every(n=>form.elements[n].reportValidity()))return;step=Math.min(step+1,steps.length-1);localStorage.setItem('jk-intake-draft',JSON.stringify(payload()));render();scrollTo(0,0)};
document.getElementById('back').onclick=()=>{step=Math.max(0,step-1);render();scrollTo(0,0)};
form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;const token=sessionStorage.getItem('jk-onboarding-token')||new URLSearchParams(location.search).get('token');if(!token){document.getElementById('status').textContent='This onboarding link is not authenticated. Return to your payment-complete link.';return}document.getElementById('status').textContent='Saving your business profile…';try{const r=await fetch('/api/onboarding/submit',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify(payload())});const out=await r.json();if(!r.ok)throw new Error(out.error||'submission failed');sessionStorage.setItem('jk-onboarding-token',token);document.getElementById('status').textContent=`Saved. Profile ${out.profile_id} is now ${out.state}.`;document.getElementById('preview').textContent=JSON.stringify(out,null,2)}catch(err){document.getElementById('status').textContent=`Could not save: ${err.message}`}});
async function bootstrapAuth(){const q=new URLSearchParams(location.search);const qtok=q.get('token');if(qtok){sessionStorage.setItem('jk-onboarding-token',qtok);history.replaceState({},'',location.pathname+location.search.replace(/([?&])token=[^&]*/,'$1').replace(/[?&]$/,''));return}const sid=q.get('session_id');if(sid&&!sessionStorage.getItem('jk-onboarding-token')){document.getElementById('status').textContent='Verifying your payment…';try{const r=await fetch('/api/onboarding/claim',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({checkout_session_id:sid})});const out=await r.json();if(!r.ok)throw new Error(out.error||'payment verification failed');sessionStorage.setItem('jk-onboarding-token',out.onboarding_token);document.getElementById('status').textContent='Payment verified. Your private client profile is ready.';history.replaceState({},'',out.redirect)}catch(err){document.getElementById('status').textContent=`Could not verify payment: ${err.message}`}}}render();bootstrapAuth();
